Develop
strange-v/car-telemetry pull request #19
Opened 2021-02-16 20:19 UTC by 3ipp0

New PR from dev to main.

2021-02-25 08:12 UTC, strange-v requested changes

2021-02-25 08:12 UTC, strange-v commented on Software/CT.BusinessLogic/Services/SerialSettings.cs
> +    class SerialSettings
It isn't a service, why it placed in the services directory?

2021-02-25 08:12 UTC, strange-v commented on Software/CT.Web/Pages/Index.razor.cs
> +                await Task.Delay(300);
o_O

2021-02-25 08:12 UTC, strange-v commented on Software/CT.BusinessLogic/Services/CanHandlers/HandlersSequence.cs
> +    public class HandlersSequence : AbstractHandler
I'd create a separate service from this with bigger responsibilities. Let's discuss this at the meeting.

2021-02-25 18:57 UTC, 3ipp0 commented on Software/CT.BusinessLogic/Services/SerialService.cs
> +                //ToDo: Handle Exception VF
:)

2021-02-25 19:02 UTC, Anbashman commented on Software/CT.Web/Pages/Index.razor
> +            <h1>@DateTime.Now.ToString("HH:mm")</h1>
I don't know how this magic works, but it updates itself

2021-02-25 19:32 UTC, Anbashman commented on Software/CT.BusinessLogic/Services/SerialSettings.cs
> +    class SerialSettings
This file is not required

2021-02-26 18:55 UTC, f1andrew commented on Hardware/CAN-receiver/CAN-receiver.ino
> +  if (can.receive(id, fltIdx, rxbytes) > -1) {
-1 is default return value of receive() function in exoCAN library. This approach taken from library example.

2021-02-28 11:26 UTC, merged